# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(help_text='Unique value for product page URL, created from name.', max_length=50, unique=True),
        ),
    ]
